server:
  port: 443
spring:
  data:
    mongodb:
      database: library

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mongock:
    runner-type: "ApplicationRunner" # default
    #runner-type: "InitializingBean"
    change-logs-scan-package:
      - ru.otus.spring.mongock.changelog

