server:
  port: 8086
  # The format used for the keystore. It could be set to JKS in case it is a JKS file
  ssl:
    enabled: true
    key-store-type: PKCS12
    # The path to the keystore containing the certificate
    key-store: classpath:ssl/baeldung.p12
    # The password used to generate the certificate
    key-store-password: 919556656_f

spring:
  data:
    mongodb:
      database: library

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mongock:
    runner-type: "ApplicationRunner" # default
    #runner-type: "InitializingBean"
    change-logs-scan-package:
      - ru.otus.spring.mongock.changelog

